# Generated by Django 4.1.7 on 2023-03-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yahoo_suffix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('digits', models.IntegerField(default=5)),
                ('tick_size', models.FloatField(default=0)),
                ('swap_long', models.FloatField(default=0)),
                ('swap_short', models.FloatField(default=0)),
                ('last_bid', models.FloatField(default=0)),
                ('last_ask', models.FloatField(default=0)),
                ('base_currency', models.CharField(max_length=50)),
                ('quote_currency', models.CharField(max_length=50)),
                ('pip_position', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('1', 'forex'), ('2', 'stock'), ('3', 'futures'), ('4', 'cfd'), ('5', 'crypto')], default=1, max_length=2)),
                ('seac_best_year', models.PositiveIntegerField(default=1)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='marketdata.broker')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Quote Date')),
                ('date_timestamp', models.FloatField(default=0)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField(default=0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='marketdata.symbol')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('date', 'symbol'), name='unique_quote'),
        ),
    ]
