# Generated by Django 4.1.7 on 2023-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_alter_symbol_standard_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='yahoo_suffix',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
