# Generated by Django 4.1.7 on 2023-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_alter_symbol_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name_plural': 'Corretoras'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ('ticker',), 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterField(
            model_name='symbol',
            name='tick_size',
            field=models.FloatField(default=0.01),
        ),
    ]
