# Generated by Django 4.1.7 on 2023-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0006_alter_broker_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
