# Generated by Django 4.1.7 on 2023-03-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0007_alter_symbol_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='marketdata.broker'),
        ),
    ]
