# Generated by Django 4.1.7 on 2023-03-11 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0010_symbol_country_symbol_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('resample', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Volatility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_periods', models.PositiveIntegerField(default=5)),
                ('trigger', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='marketdata.symbol')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='strategies.timeframe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
