# Generated by Django 4.1.7 on 2023-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_volatility_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='volatility',
            name='sharpe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volatility',
            name='signal',
            field=models.IntegerField(default=0),
        ),
    ]
