# Generated by Django 4.1.7 on 2023-03-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_param_player_strategy_delete_volatility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='log_periods',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trigger',
        ),
    ]
