# Generated by Django 4.1.7 on 2023-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframe',
            name='full_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
