# Generated by Django 4.1.7 on 2023-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_timeframe_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volatility',
            options={'verbose_name_plural': 'Volatilities'},
        ),
    ]
