# Generated by Django 4.1.7 on 2023-03-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_alter_volatility_log_periods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volatility',
            name='factor',
            field=models.FloatField(default=0.25),
        ),
    ]
