# Generated by Django 4.1.7 on 2023-03-18 22:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0010_symbol_country_symbol_currency'),
        ('strategies', '0006_volatility_sharpe_volatility_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=0.25)),
                ('sharpe', models.FloatField(default=0)),
                ('signal', models.IntegerField(default=0)),
                ('log_periods', models.PositiveIntegerField(default=20)),
                ('trigger', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Strategy Name')),
                ('potential_text', models.CharField(default='Potential', max_length=100, null=True)),
                ('trigger_text', models.CharField(default='Signal', max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('multi_timeframe', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Volatility',
        ),
        migrations.AddField(
            model_name='player',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strat_vol', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='player',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strat_vol', to='marketdata.symbol'),
        ),
        migrations.AddField(
            model_name='player',
            name='timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strat_vol', to='strategies.timeframe'),
        ),
        migrations.AddField(
            model_name='param',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='strategies.player'),
        ),
    ]
