# Generated by Django 4.1.7 on 2023-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.CharField(default='xxxxxxx', max_length=250),
        ),
    ]
