# Generated by Django 4.1.7 on 2023-03-18 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0007_param_player_strategy_delete_volatility_and_more'),
        ('marketdata', '0010_symbol_country_symbol_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=250)),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('token', models.CharField(max_length=250)),
                ('server', models.CharField(choices=[('R', 'REAL'), ('D', 'DEMO')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_price', models.FloatField(default=0)),
                ('exit_price', models.FloatField(default=0)),
                ('result', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trader.account')),
                ('strategies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='strategies.strategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketdata.symbol')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='trader.broker'),
        ),
    ]
