# Generated by Django 4.1.7 on 2023-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0009_alter_symbol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='country',
            field=models.CharField(default='BR', max_length=3),
        ),
        migrations.AddField(
            model_name='symbol',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
    ]
